from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Dict, List


@dataclass(frozen=True)
class FieldSpec:
    group: str
    field_name: str
    definition: str
    guidance_to_find: str
    example_pdf_like_text: str
    expected_answer: str
    format_note: str


def fs(
    group: str,
    field_name: str,
    definition: str,
    guidance_to_find: str,
    example_pdf_like_text: str,
    expected_answer: str,
    format_note: str,
) -> FieldSpec:
    return FieldSpec(
        group=group,
        field_name=field_name,
        definition=definition,
        guidance_to_find=guidance_to_find,
        example_pdf_like_text=example_pdf_like_text,
        expected_answer=expected_answer,
        format_note=format_note,
    )


FIELD_SPECS: List[FieldSpec] = [
    fs(
        "File_information",
        "file_name",
        "Local source PDF file name.",
        "Take from the local file path or uploaded file metadata, not from paper body text.",
        "Input file: pdf_files/Lee_2024_high_voltage_electrolytes.pdf",
        "Lee_2024_high_voltage_electrolytes.pdf",
        "string or null",
    ),
    fs(
        "File_information",
        "journal_name",
        "Journal title for the paper.",
        "Usually on the first page, publisher block, citation line, or header/footer.",
        "Journal of Power Sources 612 (2024) 234567",
        "Journal of Power Sources",
        "string or null",
    ),
    fs(
        "File_information",
        "doi",
        "Digital Object Identifier of the paper.",
        "Usually on the first page, citation block, or footer. Capture exactly as written.",
        "https://doi.org/10.1016/j.jpowsour.2024.234567",
        "10.1016/j.jpowsour.2024.234567",
        "string or null",
    ),
    fs(
        "File_information",
        "paper_title",
        "Title of the paper.",
        "Usually at the top of the first page.",
        "Electrolytes Containing Ionic Liquids for Improved Safety of Lithium-ion Batteries",
        "Electrolytes Containing Ionic Liquids for Improved Safety of Lithium-ion Batteries",
        "string or null",
    ),
    fs(
        "File_information",
        "num_electrolytes",
        "Number of distinct electrolyte formulations explicitly compared or described in the paper.",
        "Count electrolyte labels or distinct formulations across tables, figures, and methods.",
        "The study compares LiEMIBF4, GLiEMIBF4, LiBF4-GBL/EC, and Neat EMI-BF4.",
        "4",
        "integer or null",
    ),
    fs(
        "File_information",
        "tested_electrolytes_list",
        "List of distinct electrolyte names explicitly compared or described in the paper.",
        "Compile from composition tables, performance plots, and electrolyte naming definitions.",
        "LiEMIBF4, GLiEMIBF4, LiBF4-GBL/EC, and Neat EMI-BF4 were evaluated.",
        "['LiEMIBF4', 'GLiEMIBF4', 'LiBF4-GBL/EC', 'Neat EMI-BF4']",
        "JSON array or []",
    ),
    fs(
        "Information",
        "Electrolyte_Name",
        "Name or abbreviation used by the paper for the electrolyte.",
        "Look in electrolyte tables, legends, methods, and figure labels.",
        "The optimized formulation was denoted LiFSI-1.2DME-3TTE.",
        "LiFSI-1.2DME-3TTE",
        "string or null",
    ),
    fs(
        "Information",
        "Is_Optimized",
        'Whether this electrolyte is explicitly presented as optimized ("yes" or "no").',
        'Use "yes" only if the paper explicitly says optimized, selected, or best-performing. Use "no" for comparison/control alternatives. Otherwise null.',
        "Among all candidates, LiFSI-1.2DME-3TTE was selected as the optimized electrolyte.",
        "yes",
        '"yes", "no", or null',
    ),
    fs(
        "Information",
        "Electrolyte_Formulation_Details",
        "Detailed text description of how this electrolyte is formulated.",
        "Read the electrolyte preparation subsection, composition table, and reagent descriptions.",
        "LiFSI-1.2DME-3TTE was prepared by dissolving LiFSI in DME with a molar ratio coefficient of 1.2, followed by adding TTE with a coefficient of 3.",
        "LiFSI dissolved in DME with a molar ratio coefficient of 1.2, followed by TTE diluent with a coefficient of 3.",
        "string or null",
    ),
    fs(
        "Property",
        "esw_high",
        "Oxidation onset voltage / high electrochemical stability limit.",
        "Look in LSV or CV plots, figure captions, property tables, or SI.",
        "The oxidation onset was observed at 5.0 V on Pt.",
        "5.0 V (Pt)",
        "<Value> V (<Electrode_Type>)",
    ),
    fs(
        "Property",
        "esw_low",
        "Reduction onset voltage / low electrochemical stability limit.",
        "Look in LSV or CV plots, figure captions, property tables, or SI.",
        "The reduction onset was measured to be 2.25 V using a glassy carbon electrode.",
        "2.25 V (Glassy Carbon)",
        "<Value> V (<Electrode_Type>)",
    ),
    fs(
        "Property",
        "ionic_conductivity",
        "Ionic conductivity together with the temperature at which it was measured.",
        "Usually in a property table, methods, or supporting information.",
        "The electrolyte showed ionic conductivities of 4.1 mS cm-1 at 25 °C and 5.1 mS cm-1 at 30 °C.",
        "[4.1 mS/cm, 25 °C], [5.1 mS/cm, 30 °C]",
        "[Value1, Temp1], [Value2, Temp2], ...",
    ),
    fs(
        "Property",
        "viscosity",
        "Dynamic viscosity together with the temperature at which it was measured.",
        "Look in physical property tables or supporting information.",
        "The viscosities were 3.3 mPa·s at 25 °C and 4.3 mPa·s at 30 °C.",
        "[3.3 mPa·s, 25 °C], [4.3 mPa·s, 30 °C]",
        "[Value1, Temp1], [Value2, Temp2], ...",
    ),
    fs(
        "Property",
        "density",
        "Density together with the temperature at which it was measured.",
        "Look in physical property tables or supporting information.",
        "The densities were 1.09 g cm-3 at 25 °C and 1.01 g cm-3 at 30 °C.",
        "[1.09 g/cm³, 25 °C], [1.01 g/cm³, 30 °C]",
        "[Value1, Temp1], [Value2, Temp2], ...",
    ),
    fs(
        "Composition",
        "Num_Salt",
        "Number of salt components in the electrolyte.",
        "Count only components explicitly identified as salts.",
        "The binary-salt electrolyte consisted of LiFSI and LiBOB.",
        "2",
        "integer or null",
    ),
    fs(
        "Composition",
        "Salt_Type_Abbr",
        "List of salt abbreviations.",
        "Use author-defined abbreviations from methods or tables.",
        "The salts used were LiFSI and LiBOB.",
        "['LiFSI', 'LiBOB']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Salt_Type_Full",
        "List of full chemical names of salts.",
        "Use full names only when explicitly defined in the paper.",
        "LiFSI (lithium bis(fluorosulfonyl)imide) and LiBOB (lithium bis(oxalate)borate) were employed.",
        "['Lithium bis(fluorosulfonyl)imide', 'Lithium bis(oxalate)borate']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Salt_Composition",
        "Primary quantitative value(s) for salt concentration or coefficient.",
        "Take the numeric values aligned to each salt entry.",
        "The binary-salt formulation used 0.6 M LiFSI and 0.4 M LiBOB.",
        "['0.6', '0.4']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Salt_Composition_Type",
        "Unit or context for each salt composition value.",
        "Take the unit or context label aligned to each salt entry.",
        "The concentrations were 0.6 M LiFSI and 0.4 M LiBOB.",
        "['M', 'M']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Num_Solvent",
        "Number of solvent components.",
        "Count only solvents, excluding salts, diluents, and additives.",
        "The solvent mixture consisted of EC, DMC, and EMC.",
        "3",
        "integer or null",
    ),
    fs(
        "Composition",
        "Solvent_Type_Abbr",
        "List of solvent abbreviations.",
        "Take author-defined abbreviations in the order given.",
        "EC, DMC, and EMC were used as the solvent system.",
        "['EC', 'DMC', 'EMC']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Solvent_Type_Full",
        "List of full chemical names of solvents.",
        "Use only the paper-defined full names.",
        "The solvent mixture was composed of ethylene carbonate, dimethyl carbonate, and ethyl methyl carbonate.",
        "['Ethylenecarbonate', 'Dimethylcarbonate', 'Ethylmethylcarbonate']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Solvent_Ratio",
        "Ratio among solvents or solvent molar ratio coefficient.",
        "Look for 1:1:1-style ratios or coefficient values associated with the solvent system.",
        "EC/DMC/EMC was used in a volume ratio of 1:1:1.",
        "1:1:1",
        "string or null",
    ),
    fs(
        "Composition",
        "Solvent_Ratio_Type",
        "Type or context of Solvent_Ratio.",
        "Look for nearby labels such as volume ratio, molar ratio coefficient, or mass ratio.",
        "EC/DMC/EMC was used in a volume ratio of 1:1:1.",
        "volume ratio",
        "string or null",
    ),
    fs(
        "Composition",
        "Num_Diluent",
        "Number of diluent components.",
        "Count only components explicitly described as diluents.",
        "TTE served as the sole diluent in the LHCE formulation.",
        "1",
        "integer or null",
    ),
    fs(
        "Composition",
        "Diluent_Type_Abbr",
        "List of diluent abbreviations.",
        "Use author-defined abbreviations only when the paper explicitly calls the component a diluent.",
        "TTE was introduced as the fluorinated diluent.",
        "['TTE']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Diluent_Type_Full",
        "List of full chemical names of diluents.",
        "Use full names only when defined in the paper.",
        "TTE (1,1,2,2-tetrafluoroethyl-2,2,3,3-tetrafluoropropyl ether) was used as the diluent.",
        "['1,1,2,2-tetrafluoroethyl-2,2,3,3-tetrafluoropropyl ether']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Diluent_Composition",
        "Numerical value(s) for diluent composition or coefficient.",
        "Take the explicit numeric value tied to each diluent.",
        "The optimized LHCE contained TTE with a molar ratio coefficient of 3.",
        "['3']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Diluent_Composition_Type",
        "Unit or context for each diluent composition value.",
        "Take the nearby unit or label such as molar ratio coefficient.",
        "The optimized LHCE contained TTE with a molar ratio coefficient of 3.",
        "['molar ratio coefficient']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Num_Additive",
        "Number of additive components.",
        "Count only components explicitly described as additives.",
        "TPB was introduced as the only additive in the control electrolyte.",
        "1",
        "integer or null",
    ),
    fs(
        "Composition",
        "Additive_Type_Abbr",
        "List of additive abbreviations.",
        "Use author-defined additive abbreviations only.",
        "TPB was added to suppress interfacial degradation.",
        "['TPB']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Additive_Type_Full",
        "List of full chemical names of additives.",
        "Use full names only when explicitly defined.",
        "TPB (triphenyl borate) was used as the additive.",
        "['Triphenyl borate']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Additive_Ratio",
        "Additive concentration value(s).",
        "Look in the formulation details or methods.",
        "The electrolyte contained 10 wt% TPB.",
        "['10']",
        "JSON array or null",
    ),
    fs(
        "Composition",
        "Additive_Ratio_Unit",
        "Unit associated with Additive_Ratio.",
        "Take the exact unit next to the additive concentration.",
        "The electrolyte contained 10 wt% TPB.",
        "['wt%']",
        "JSON array or null",
    ),
    fs(
        "Common_condition",
        "Separator",
        "Separator material and specification.",
        "Look in cell assembly, methods, or experimental tables.",
        "A PP separator (Celgard 2400) was used.",
        "PP (Celgard 2400)",
        "string or null",
    ),
    fs(
        "Common_condition",
        "Anode_Active_Material_Type",
        "Standardized anode active material class.",
        "Look in electrode preparation or cell assembly sections.",
        "The graphite anode was paired with NMC811.",
        "Graphite (Gr)",
        'one of ["Graphite (Gr)", "LTO", "Silicon (Si)", "SiOx (Silicon Oxide)", "Si-C Composite", "Li Metal", "HC (Hard Carbon)", "SC (Soft Carbon)", "MCMB", "Anode-Free", "Others"] or null',
    ),
    fs(
        "Common_condition",
        "Anode_Active_Material_Details",
        "Specific details of the anode active material itself.",
        "Use the specific chemistry or descriptor excluding binder and conductive additive.",
        "Artificial graphite was used for the anode.",
        "Artificial graphite",
        "string or null",
    ),
    fs(
        "Common_condition",
        "Anode_Si_Content_wt",
        "Wt% of silicon or silicon-based material in the anode active material blend.",
        "Look for explicit silicon fraction in the anode composition discussion.",
        "The graphite anode contained 0 wt% silicon.",
        "0 wt%",
        "string or null",
    ),
    fs(
        "Common_condition",
        "Cathode_Active_Material_Type",
        "Standardized cathode active material class.",
        "Look in electrode preparation or cell assembly sections.",
        "NMC811 cathodes were used throughout.",
        "NMC",
        'one of ["NMC", "NCA", "NCMA", "LMO", "LCO", "LFP", "LMFP", "LNMO", "LMR", "LRLO", "LNO", "HE-NMC", "NFM", "NVM", "PBA", "Sulfur", "Others"] or null',
    ),
    fs(
        "Common_condition",
        "Cathode_Active_Material_Details",
        "Specific formula and composition of the cathode active material.",
        "Use the detailed chemistry from methods or materials.",
        "LiNi0.8Mn0.1Co0.1O2 (NMC811) was used as the cathode.",
        "LiNi0.8Mn0.1Co0.1O2 (NMC811)",
        "string or null",
    ),
    fs(
        "Common_condition",
        "Cell_type",
        "Physical form factor of the test cell.",
        "Look in cell assembly or experimental section.",
        "CR2032 coin cells were assembled in an Ar-filled glovebox.",
        "coin cell",
        'one of ["coin cell", "pouch cell", "cylindrical cell", "prismatic cell", "swagelok", "others"] or null',
    ),
    fs(
        "Common_condition",
        "Cell_type_details",
        "Specific physical/mechanical cell hardware details.",
        "If the paper provides structured details, keep them as a JSON-like string.",
        'CR2032 stainless-steel coin cells with crimp sealing were used.',
        '{"coin_cell_model": "2032", "coin_cell_case_material": "stainless steel", "coin_cell_seal_type": "crimp sealing"}',
        "string or null",
    ),
    fs(
        "Common_condition",
        "cell_mode",
        "Electrode pairing with configuration label.",
        "Look in the electrochemical test description or figure captions.",
        "Graphite || Li half-cells were used for formation and cycling tests.",
        "Graphite || Li (half-cell)",
        "<Cathode Electrode> || <Anode Electrode> (<configuration>) or null",
    ),
    fs(
        "Common_condition",
        "electrolyte_loading",
        "Amount of electrolyte injected relative to capacity or volume.",
        "Look in cell assembly details or footnotes of methods tables.",
        "The electrolyte loading was 3.0 g Ah-1.",
        "3.0 g/Ah",
        "string or null",
    ),
    fs(
        "Formation",
        "formation_wetting_voltage",
        "Voltage held during electrolyte wetting.",
        "Look in formation or pre-wetting protocol description.",
        "Cells were wetted at 1.5 V for 16 h before formation.",
        "1.5 V",
        "string or null",
    ),
    fs(
        "Formation",
        "formation_wetting_time",
        "Duration of electrolyte wetting.",
        "Look in formation or pre-wetting protocol description.",
        "Cells were wetted at 1.5 V for 16 h before formation.",
        "16 h",
        "string or null",
    ),
    fs(
        "Formation",
        "formation_wetting_temperature",
        "Temperature during electrolyte wetting.",
        "Look in formation or wetting protocol description.",
        "Wetting was performed at 25 °C.",
        "25 °C",
        "string or null",
    ),
    fs(
        "Formation",
        "formation_cycle_protocol",
        "Charge/discharge steps used in formation.",
        "Look in methods, electrochemical measurements, or SI protocol tables.",
        "Formation consisted of 1 cycle at 0.1 C between 2.0 and 4.65 V at 25 °C.",
        "[Formation: 1 cycle at 0.1 C between 2.0–4.65 V at 25°C] (Electrochemical Measurements)",
        'string or null; preferred style "[Step1], [Step2], ... (Source)"',
    ),
    fs(
        "Formation",
        "formation_initial_coulombic_efficiency",
        "Initial Coulombic Efficiency of the formation cycle.",
        "Look for ICE in formation results or the first-cycle discussion.",
        "The initial Coulombic Efficiency was 91.5%.",
        "91.5 %",
        "string or null",
    ),
    fs(
        "Cycling_test",
        "cycle_operating_voltage_range",
        "Voltage window applied during cycling.",
        "Look in cycling methods, figures, or captions.",
        "Cells were cycled between 2.7 and 4.6 V.",
        "2.7 – 4.6 V",
        "string or null",
    ),
    fs(
        "Cycling_test",
        "cycle_T",
        "Temperature during cycling.",
        "Look in cycling methods, captions, or figure notes.",
        "Cycling was conducted at 25 °C.",
        "25 °C",
        "string or null",
    ),
    fs(
        "Cycling_test",
        "cycle_charge_C",
        "Charge C-rate used in cycling.",
        "Look in electrochemical cycling protocol description.",
        "Cells were charged at 0.5 C and discharged at 0.2 C.",
        "0.5 C",
        "string or null",
    ),
    fs(
        "Cycling_test",
        "cycle_discharge_C",
        "Discharge C-rate used in cycling.",
        "Look in electrochemical cycling protocol description.",
        "Cells were charged at 0.5 C and discharged at 0.2 C.",
        "0.2 C",
        "string or null",
    ),
    fs(
        "Cycling_test",
        "cycle_life_retention_pair",
        "Cycling result as [N cycle, retention %] pairs.",
        "Extract from tables or digitized plot points. Keep explicit cycle labels when available.",
        "Capacity retentions at 300, 400, and 500 cycles were 81.2%, 80.0%, and 79.2%, respectively.",
        "[300 cycle, 81.2 %], [400 cycle, 80.0 %], [500 cycle, 79.2 %]",
        "A2R source field",
    ),
    fs(
        "Cycling_test",
        "cycle_initial_discharge_capacity",
        "Initial discharge capacity at the start of cycling.",
        "Look for first-cycle discharge capacity in cycling performance discussion or figure captions.",
        "The initial discharge capacity was 154.2 mAh g-1.",
        "154.2 mAh/g",
        "string or null",
    ),
    fs(
        "Cycling_test",
        "cycle_discharge_capacity",
        "Discharge capacity at cycle N corresponding to cycle_life_retention_pair.",
        "If a cycle-specific capacity series is given, preserve cycle labels when possible.",
        "The discharge capacities at 300, 400, and 500 cycles were 125.5, 115.5, and 105.5 mAh g-1.",
        "[300 cycle, 125.5 mAh/g], [400 cycle, 115.5 mAh/g], [500 cycle, 105.5 mAh/g]",
        "A2R source field",
    ),
    fs(
        "Rate_test",
        "rate_operating_voltage_range",
        "Voltage window applied during rate capability testing.",
        "Look in rate protocol description or rate plot caption.",
        "Rate tests were performed between 2.7 and 4.6 V.",
        "2.7 – 4.6 V",
        "string or null",
    ),
    fs(
        "Rate_test",
        "rate_T",
        "Temperature during rate testing.",
        "Look in rate capability methods or figure captions.",
        "Rate capability was evaluated at 25 °C.",
        "25 °C",
        "string or null",
    ),
    fs(
        "Rate_test",
        "rate_retention_pair",
        "Rate capability results as [charge-C, discharge-C, retention%] tuples.",
        "Extract from tables or rate capability plots.",
        "The retention values were 100% at 0.1/0.1 C, 92% at 1/1 C, and 75% at 5/5 C.",
        "[0.1 C, 0.1 C, 100 %], [1 C, 1 C, 92 %], [5 C, 5 C, 75 %]",
        "A2R source field",
    ),
    fs(
        "Storage_test",
        "storage_T",
        "Temperature during storage testing.",
        "Look in storage/calendar-life methods or captions.",
        "Cells were stored at 55 °C.",
        "55 °C",
        "string or null",
    ),
    fs(
        "Storage_test",
        "storage_SOC_initial",
        "Initial state of charge at start of storage.",
        "Look in storage protocol text or figure caption.",
        "Storage started from 100% SOC.",
        "100%",
        "string or null",
    ),
    fs(
        "Storage_test",
        "storage_initial_voltage",
        "Open-circuit voltage at the beginning of storage.",
        "Look in storage protocol text or data table.",
        "The initial OCV before storage was 4.6 V.",
        "4.6 V",
        "string or null",
    ),
    fs(
        "Storage_test",
        "storage_voltage",
        "Voltage vs storage time pairs.",
        "Extract explicit time/value pairs from tables or storage plots.",
        "The OCV values were 3.2 V at 7 days, 3.15 V at 14 days, and 3.1 V at 30 days.",
        "[7 days, 3.2 V], [14 days, 3.15 V], [30 days, 3.1 V]",
        "A2R source field",
    ),
    fs(
        "Storage_test",
        "storage_gas_volume",
        "Gas volume vs storage time pairs.",
        "Extract explicit time/value pairs from tables or gas-evolution plots.",
        "Gas volumes reached 15 mL at 7 days, 35 mL at 14 days, and 85 mL at 30 days.",
        "[7 days, 15 mL], [14 days, 35 mL], [30 days, 85 mL]",
        "A2R source field",
    ),
    fs(
        "Storage_test",
        "storage_swelling",
        "Swelling vs storage time pairs.",
        "Extract explicit time/value pairs from thickness or swelling plots.",
        "Swelling values were 2% at 7 days, 5% at 14 days, and 12% at 30 days.",
        "[7 days, 2 %], [14 days, 5 %], [30 days, 12 %]",
        "A2R source field",
    ),
    fs(
        "Storage_test",
        "storage_DCIR_change",
        "DCIR change vs storage time pairs.",
        "Extract explicit time/value pairs from resistance plots or tables.",
        "DCIR increases were 3% at 7 days, 8% at 14 days, and 20% at 30 days.",
        "[7 days, 3 %], [14 days, 8 %], [30 days, 20 %]",
        "A2R source field",
    ),
    fs(
        "Storage_test",
        "storage_capacity",
        "Capacity retention vs storage time pairs.",
        "Extract explicit time/value pairs from storage-retention plots or tables.",
        "Capacity retentions were 99% at 7 days, 98.5% at 14 days, and 96.2% at 30 days.",
        "[7 days, 99 %], [14 days, 98.5 %], [30 days, 96.2 %]",
        "A2R source field",
    ),
    fs(
        "RPT_test",
        "rpt_operating_voltage_range",
        "Voltage window used during RPT/check-up cycles.",
        "Look in RPT/check-up methods or captions.",
        "RPT check-up cycles were run between 2.7 and 4.6 V.",
        "2.7 – 4.6 V",
        "string or null",
    ),
    fs(
        "RPT_test",
        "rpt_T",
        "Temperature during RPT/check-up cycles.",
        "Look in the RPT/check-up method or figure caption.",
        "RPT was conducted at 25 °C.",
        "25 °C",
        "string or null",
    ),
    fs(
        "RPT_test",
        "rpt_c_rate",
        "Low C-rate used for RPT/check-up capacity measurement.",
        "Look in RPT method or experimental section.",
        "RPT capacity was measured at 0.2 C.",
        "0.2 C",
        "string or null",
    ),
    fs(
        "RPT_test",
        "rpt_capacity",
        "RPT capacity vs cycle pairs.",
        "Extract explicit cycle/value pairs from tables or plots.",
        "RPT capacities were 160.2 mAh g-1 at 0 cycle, 155.1 at 100 cycles, and 148.5 at 200 cycles.",
        "[0 cycle, 160.2 mAh/g], [100 cycle, 155.1 mAh/g], [200 cycle, 148.5 mAh/g]",
        "A2R source field",
    ),
    fs(
        "RPT_test",
        "rpt_resistance",
        "RPT resistance vs cycle pairs.",
        "Extract explicit cycle/value pairs from resistance plots or tables.",
        "Internal resistances were 25.1 Ω at 0 cycle, 32.4 Ω at 100 cycles, and 45.8 Ω at 200 cycles.",
        "[0 cycle, 25.1 Ω], [100 cycle, 32.4 Ω], [200 cycle, 45.8 Ω]",
        "A2R source field",
    ),
    fs(
        "RPT_test",
        "rpt_swelling",
        "RPT swelling vs cycle pairs.",
        "Extract explicit cycle/value pairs from swelling plots or tables.",
        "Cell swelling values were 0% at 0 cycle, 2.5% at 100 cycles, and 5.8% at 200 cycles.",
        "[0 cycle, 0 %], [100 cycle, 2.5 %], [200 cycle, 5.8 %]",
        "A2R source field",
    ),
    fs(
        "Test_shared",
        "test_condition_distinctness",
        "Short note about unique test conditions not captured by the structured condition fields.",
        "Look for notes like pre-storage before measurement, room-temperature measurement after high-temperature storage, or special hold/rest conditions.",
        "Stored at 80 °C for 4 h; discharge tested at room temperature.",
        "Stored at 80 °C for 4 h; discharge tested at room temperature.",
        "string or null",
    ),
]


def field_specs_as_dicts() -> List[Dict[str, str]]:
    return [asdict(spec) for spec in FIELD_SPECS]


def compact_field_reference() -> str:
    lines: List[str] = []
    for spec in FIELD_SPECS:
        lines.append(
            f"- {spec.field_name} ({spec.group}): {spec.definition} "
            f"Guidance: {spec.guidance_to_find} "
            f"Preferred output style: {spec.format_note}."
        )
    return "\n".join(lines)